### ISSUE TITLE
failed to create host: Image windows-server-2019 is not compatible with resource class l1.medium

### ISSUE THREAD

**Issue by cadesalaberry** [CircleCI-Public/windows-preview-docs#11]
I ran into this error when trying the default options in the `config.yml`:

```yml
version: 2.1

orbs:
  windows-tools: circleci/windows-tools@0.0.4

jobs:
  build:
    executor:
      name: windows-tools/preview-default
      shell: bash.exe
    steps:
      - checkout
      - run: ls -lah
      - run:
          command: ping circleci.com
          shell: cmd.exe
      - run:
          command: echo 'This is powershell'
          shell: powershell.exe
```

```
Build-agent version 1.0.12069-0bafdb01 (2019-07-05T21:14:34+0000)
Creating a dedicated VM with windows-server-2019 image
failed to create host: Image windows-server-2019 is not compatible with resource class l1.medium

failed to create host: Image windows-server-2019 is not compatible with resource class l1.medium
```

Do you have any insight on what I could do to make it work out ?

**Comment by glenjamin** [comment]
Do you have a link to the project?

Has your account been enabled?
https://github.com/CircleCI-Public/windows-preview-docs#prerequisites-to-try-out-windows-on-circleci

**Comment by cadesalaberry** [comment]
- [x] Your organization is using a [Performance plan](https://circleci.com/pricing/usage/) or is on a Performance plan trial
- [x] Your project has [pipelines enabled](https://circleci.com/docs/2.0/build-processing/)

The repo is not public: https://circleci.com/gh/padoa/PadoaDevicesManager/24

**Comment by appplemac** [comment]
Hey @cadesalaberry, thanks for your patience here. Your org should now have Windows access. A feature flag was set incorrectly on our side. Please let me know if this fixes it.

**Comment by cadesalaberry** [comment]
@appplemac Thanks a lot ! everything is now running smoothly.
