### ISSUE TITLE
Install CircleCI CLI

### ISSUE THREAD

**Issue by trieloff** [CircleCI-Public/windows-preview-docs#12]
It would be great if the `circleci` CLI was pre-installed, so that tests can be run in parallel.

**Comment by marcomorain** [comment]
Thanks @trieloff - we've created a JIRA ticket `CIRCLE-19731` to track this in our  system.

**Comment by ericfode** [comment]
@trieloff please give it a shot. I think it works now!

**Comment by trieloff** [comment]
Is that orb version `0.0.5` or higher?
